name: pingipool_1_0
description: Pingipool 1.0 AI Chat App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/bot_avatar.png
    - assets/images/splash_image.png
    - assets/images/neurali.png
    - assets/images/icon.png

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Italic.ttf
          style: italic
